### ISSUE TITLE
x-IMU missing libraries

### ISSUE THREAD

**Issue by tychonas** [jamiebullock/IMU2OSC#4]
HERE IT IS THE REPORT

Process:         IMU2OSC [7251]
Path:            /Users/USER/Documents/*/IMU2OSC.app/Contents/MacOS/IMU2OSC
Identifier:      jamiebullock.IMU2OSC
Version:         ??? (0.1)
Code Type:       X86-64 (Native)
Parent Process:  launchd [130]

Date/Time:       2012-09-03 11:57:41.521 +0300
OS Version:      Mac OS X 10.7.4 (11E2620)
Report Version:  9
Sleep/Wake UUID: F115494F-7512-4A8D-8625-6D0D50683022

Interval Since Last Report:          343991 sec
Crashes Since Last Report:           4
Per-App Crashes Since Last Report:   3
Anonymous UUID:                      F0815638-8155-4579-BB2A-E1AD220B2E55

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/boost/1.49.0/lib/libboost_thread-mt.dylib
  Referenced from: /Users/USER/Documents/*/IMU2OSC.app/Contents/MacOS/IMU2OSC
  Reason: image not found

Binary Images:
       0x101a2b000 -        0x101a9efff +jamiebullock.IMU2OSC (??? - 0.1) <135CAC69-2FF9-31BF-A4DB-875252457D97> /Users/USER/Documents/*/IMU2OSC.app/Contents/MacOS/IMU2OSC
    0x7fff6162b000 -     0x7fff6165fbaf  dyld (195.6 - ???) <C58DAD8A-4B00-3676-8637-93D6FDE73147> /usr/lib/dyld

Model: MacBookPro10,1, BootROM MBP101.00EE.B00, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.3f32
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe, 1024 MB
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In, 512 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xEF), Broadcom BCM43xx 1.0 (5.106.198.19.21)
Bluetooth: Version 4.0.7f2, 2 service, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: hub_device, 0x8087  (Intel Corporation), 0x0024, 0x1a100000 / 2
USB Device: Iomega eGo HDD, 0x059b  (Iomega Corporation), 0x047c, 0x1a120000 / 4
USB Device: FaceTime HD Camera (Built-in), apple_vendor_id, 0x8510, 0x1a110000 / 3
USB Device: hub_device, 0x8087  (Intel Corporation), 0x0024, 0x1d100000 / 2
USB Device: hub_device, 0x0424  (SMSC), 0x2512, 0x1d180000 / 3
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0263, 0x1d182000 / 5
USB Device: BRCM20702 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x1d181000 / 4
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8286, 0x1d181300 / 8

**Comment by jamiebullock** [comment]
This is now fixed.
