### ISSUE TITLE
Less visible data on the IMU2OSC

### ISSUE THREAD

**Issue by tychonas** [jamiebullock/IMU2OSC#7]
If possible to have less data visible in the software so that the memory will not get full. if possible to write also the osc message /ximu/euler/1 ---- the data

**Comment by jamiebullock** [comment]
It now displays the numeric values in number boxes rather than a scrolling list. I think this is more useful. The current display is temporary. Eventually it will have a 3D box showing the rotation of the unit like the windows app.
